
CREATE TABLE Employee (
	id serial PRIMARY KEY,
	name VARCHAR ( 50 ) UNIQUE NOT NULL,
	age VARCHAR ( 50 ) NOT NULL,
	address VARCHAR ( 255 ) UNIQUE NOT NULL,
	mobile_number txt NOT NULL
);


CREATE TABLE IF NOT EXISTS public."Items"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default" NOT NULL,
    "Done" boolean NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Items"
    OWNER to postgres;